[project]
name = "pdf-to-csv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ollama>=0.5.1",
    "pdfplumber>=0.11.7",
]
